# Site settings
title: Everyday Engineered
header-img: img/web-development.jpg
email: scsenkowski@gmail.com
copyright_name: Ssenkowski
description: > # this means to ignore newlines until "baseurl:"
  CRUD
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  Ssenkowski
learn_profile: Ssenkowski
email_username: scsenkowski@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
